UA.UAQOgElki = function(){//'+UA.UAvtiQvcR.UAEyLkIF2183+'
    
	return {
		UAEyLkIF2190:'',
		UAEyLkIF2189:'',
		UAEyLkIF2188:'',
		UAEyLkIF2187:'',
		UAEyLkIF2186:'',
		UAEyLkIF2185:'Cookies policy',
		UAEyLkIF2184:'Privacy Policy',
		UAEyLkIF2183:'To reset the site colors, the page will be reloaded',
		UAEyLkIF2182:'Accessible print mode',
		UAEyLkIF2181:'To easily search for concepts and phrases, the accessibility menu will now close.',
		UAEyLkIF2180:'Highlighting for links canceled',
		UAEyLkIF2179:'All links were highlighted with underlined',
		UAEyLkIF2178:'The menu moved to the other side ',
		UAEyLkIF2177:'The menu size return to nurmal',
		UAEyLkIF2176:'The menu size is now bigger',
		UAEyLkIF2175:' User Guide , will open in new window',
		UAEyLkIF2174:'Color Selection menu',
		UAEyLkIF2173:'Click to close the Color Selection menu',
		UAEyLkIF2172:'The amount of spacing you want to set between text lines',
		UAEyLkIF2171:'The Language Selection menu closes',
		UAEyLkIF2170:'Continue navigating with the tab button to reach the save button.',
		UAEyLkIF2169:'The Settings menu opens',
		UAEyLkIF2168:'The Settings menu closes',
		UAEyLkIF2167:'Continue navigating to hear and select accessibility options',
		UAEyLkIF2166:"Menu opens",
		UAEyLkIF2165:'The selected tab is loaded, press a small down arrow to enter the tab contents',
		UAEyLkIF2164:'Close the preview message screen',
		UAEyLkIF2163:'Accessibility Statement',
		UAEyLkIF2162:'This option can not be enabled on smartphones and tablets',
		UAEyLkIF2161:'Open menu in accessible mode (menu will open in pop-up panel)',
		UAEyLkIF2160:'All links in the menu',
		UAbnKLYRp :"You are about to leave the pop-up panel without closing properly. If you want to close it now, press the ESC button on the keyboard. Know UAEIoBPet you may not be able to return to the panel.",
		UAPjHVnuGr : 'Close pop-up',
		UAVrhGfv : "Pop-up pane has been closed.",
		UAjaumOUw: "The beginning of a web page, click to go to the main content",
		UAxlgiZFjU: "End of a web page, you can press Enter to return to the top",
		UAmrcdlM: "You can press Enter to skip to the next area",
		UAEyLkIF2159:'close this message',
		UAEyLkIF2158:'To activate navigation by keyboard press the <span id="activateKBRbyY" role="button" tabindex="0"> Y key </span>',
		UAEyLkIF2157:'Saved successfully',
		UAEyLkIF2156:'The set: ',
		UAEyLkIF2155:'Name the adjustments you made',
		UAEyLkIF2154:'Language selected, proceed to "Change Language" button to apply the change.',
		UAEyLkIF2153:'This language is the current language',
		UAEyLkIF2152:'Change language (page will reload)',
		UAEyLkIF2151:'Soon',
		UAEyLkIF2150:"Menu language. When clicked will go to a menu that displays the languages to select for the interface. After selecting the language, navigate to the end of the list to the 'Update Language' button. Note that the page will reload.",
		UAEyLkIF2149:'Connected',
		UAEyLkIF2148:'Menu language',
		UAEyLkIF2147:'Turn off Addon on this site',
		UAEyLkIF2146:'The team behind ANDI',
		UAEyLkIF2145:'Usage Policy',
		UAEyLkIF2144:'You have logged out of your account',
		UAEyLkIF2143:'Log out from your account',
		UAEyLkIF2142:'Log in to your account',
		UAEyLkIF2141:'Log out',
		UAEyLkIF2140:'Log in',
		UAEyLkIF2139:'I agree to these terms and also understand that when choosing a language the interface may be reloaded',
		UAEyLkIF2138:'Open the main accessibility menu from anywhere on the site and press F10',
		UAEyLkIF2137:'I agree to the terms',
		UAEyLkIF2136:'More information on our use regulations.',
		UAEyLkIF2135:'To improve your browsing experience with the extension, we use cookies. By using the AddOn you agree to the use of cookies.',
		UAEyLkIF2134:'My preferred menu language is',
		UAEyLkIF2133:'Some adjustments before starting',
		UAEyLkIF2132:'F - Skip between input fields. ( If the input field is an editing field where you can enter text, this interface will be automatically disabled to allow you to type ).',
		UAEyLkIF2131:'B - Skip between buttons',
		UAEyLkIF2130:'G - Skip between images',
		UAEyLkIF2129:'H - Skip between titles',
		UAEyLkIF2128:'T - Skip between tables',
		UAEyLkIF2127:'K - Skip between links',
		UAEyLkIF2126:'I - Skip between items in the list',
		UAEyLkIF2125:'L - Skip between lists',
		UAEyLkIF2124:'By tapping one of the following letters you can easily skip between:',
		UAEyLkIF2123:"With the new interface we developed, you can now navigate by the type of information you're looking for.",
		UAEyLkIF2122:'I got it, do not show me any more',
		UAEyLkIF2121:'Reset languages',
		UAEyLkIF2120:'Change language',
		UAEyLkIF2119:'Select the interface language',
		UAEyLkIF2118:'For the following reason:',
		UAEyLkIF2117:'User has turned off the extension on the following site',
		UAEyLkIF2116:'The user did not specify why',
		UAEyLkIF2115:'Turn off, the page will reload',
		UAEyLkIF2114:'The reason I close this Addon is:',
		UAEyLkIF2113:'The plugin does not give me the accessibility I need',
		UAEyLkIF2112:'The plugin slows the site',
		UAEyLkIF2111:'The plugin breaks the site',
		UAEyLkIF2110:"It's important for us to know why you do not want the extension to run on this site",
		UAEyLkIF2109:"Don't make this site accessible",
		UAEyLkIF2108:'For example, high contrast adjust',
		UAEyLkIF2107:'Close pop-up',
		UAEyLkIF2106:'All animations Disabled',
		UAEyLkIF2105:'GIF animations Disabled',
		UAEyLkIF2104:'Stop all movement',
		UAEyLkIF2103:'The page will refresh to restore animations',
		UAEyLkIF2102:'Stop GIF animations',
		UAEyLkIF2101:'Advanced support for screen reader software has been canceled, the page will be reloaded.',
		UAEyLkIF2100:'Advanced screen reader support has been enabled',
		UAEyLkIF299:'Update exiesting set',
		UAEyLkIF298:'Save new set',
		UAEyLkIF297:'Area number',
		UAEyLkIF296:'You must enter a search term or phrase',
		UAEyLkIF295:'You can drag the button anywhere with your mouse or move it with your keyboard arrows',
		UAEyLkIF294:'Dark gray color',
		UAEyLkIF293:'Light gray color',
		UAEyLkIF292:'Brown color',
		UAEyLkIF291:'Dark orange color',
		UAEyLkIF289:'Light orange color',
		UAEyLkIF288:'yellow color',
		UAEyLkIF287:'Light green color',
		UAEyLkIF286:'Dark green color',
		UAEyLkIF285:'Turquoise color',
		UAEyLkIF284:'blue color',
		UAEyLkIF283:'purple color',
		UAEyLkIF282:'pink color',
		UAEyLkIF281:'Red color',
		UAEyLkIF280:'White color',
		UAEyLkIF279:'Backward',
		UAEyLkIF278:'Reset',
		UAEyLkIF277:'Reset all settings in this category',
		UAEyLkIF276:'By pressing the button, basic accessibility will be activated:&#xa;1. Enlargement of text &#xa;2.  Changing the font type to more readable font&#xa;3. Links will have a bottom line added&#xa;4. The mouse cursor will grow',
		UAEyLkIF275:'You can choose what to do: &#xa; 1. Make accessibility adjustments.&#xa;2. Take actions on your personal account &#xa; 3. Learn about Andy with our guide. Send us feedback about Andy, and report problems. &#xa;&#xa; You can switch between topics using the right and left arrows. To access the content, click the tab button on your keyboard. ',
		UAEyLkIF274:'Click to find out more options for customizing a site for you. &#xa; You can increase text, change spacing, select colors, search for concepts, enjoy accessible printing and much more.',
		UAEyLkIF273:'Close the menu',
		UAEyLkIF272:'Change direction',
		UAEyLkIF271:'Increase the menu',
		UAEyLkIF270:'Show this advertisement in an accessible format',
		UAEyLkIF269:'Back to image',
		UAEyLkIF268:'Live text',
		UAEyLkIF267:'Seconds',
		UAEyLkIF266:'Close this advertisement',
		UAEyLkIF265:'Close this advertisement in',
		UAEyLkIF264:'Close help',
		UAEyLkIF263:'Close help in',
		UAEyLkIF262:'This button changes the opening direction of the menu. Try now',
		UAEyLkIF261:'This button increases the menu for convenient and easy viewing. Try now',
		UAHFWoSPH:'Your request is done',
		UACwtNNo:'Starts Making your request',
		UAeQgjY:'Loading data from server',
		UAEyLkIF257:'Accessibility is ready',
		UAEyLkIF256:'Starts loading accessibility',
		UAEyLkIF255:'Reset all settings ? \n The page will reload.',
		UAEyLkIF254:'Sub menu settings has been closed',
		UAEyLkIF253:'Region targeting was canceled',
		UAEyLkIF252:'Focus mode Region activated',
		UAEyLkIF251:'Canceled status and the page will be reloaded.',
		UAEyLkIF250:'All initials have been changed to full text',
		UAEyLkIF249:'An accessible print preview window opens',
		UAEyLkIF248:'A box was opened to search for concepts from Wikipedia',
		UAEyLkIF247:'A hidden information state has been canceled',
		UAEyLkIF246:'Hidden information mode is displayed in visible mode',
		UAEyLkIF245:'VirUAEkKMFBEj keyboard canceled',
		UAEyLkIF244:'VirUAEkKMFBEj keyboard enabled',
		UAEyLkIF243:'Focus Bold was canceled',
		UAEyLkIF242:'Focus Bold was activated',
		UAEyLkIF241:'The mouse cursor has returned to its original size',
		UAEyLkIF240:'The mouse cursor was enlarged and painted white',
		UAEyLkIF239:'The mouse cursor was enlarged and painted black',
		UAEyLkIF238:'Navigate with is letters canceled ',
		UAEyLkIF237:'Navigate with is letters activated ',
		UAEyLkIF236:'Font change mode canceled',
		UAEyLkIF235:'Font type changed to Ariel',
		UAEyLkIF234:'The site has returned to normal',
		UAEyLkIF233:'The site is different to grayscale',
		UAEyLkIF232:'Bright contrast mode was canceled',
		UAEyLkIF231:'Bright contrast mode was activated',
		UAEyLkIF230:'Dark contrast mode was canceled',
		UAEyLkIF229:'Dark contrast mode was activated',
		UAEyLkIF228:'Background color canceled',
		UAEyLkIF227:'The colors you chose were saved',
		UAEyLkIF226:'Background color reset',
		UAEyLkIF225:'Background color changed',
		UAEyLkIF224:'Header color and links reset',
		UAEyLkIF223:'Headers and links color changed',
		UAEyLkIF222:'Text color reset',
		UAEyLkIF221:'Text color changed',
		UAEyLkIF220:'All text alignments have been returned to normal',
		UAEyLkIF219:'Text aligned to right',
		UAEyLkIF218:'Text is left-aligned',
		UAEyLkIF217:'The text returned to its original size',
		UAEyLkIF216:'Text has been reduced',
		UAEyLkIF215:'Text increased',
		UAEyLkIF214:'Magnifying glass stopped',
		UAEyLkIF213:'Magnifier activated',
		UAEyLkIF212:'Adjusting to navigational - Pressing the button will open a menu containing settings for this category ',
		UAEyLkIF211:'djusting color contrast - Pressing the button will open a menu containing settings for this category',
		UAEyLkIF210:'Help with understanding the content - clicking the button will open a menu UAEIoBPet contains settings for this category',
		UAEyLkIF209:'Adjust text visibility - Clicking the button will open a menu containing settings for this category',
		UAEyLkIF208:'Save and open a personal area - Once you click, you will go to a personal profile and you can save your settings',
		UAEyLkIF207:'All settings have been reset',
		UAEyLkIF206:'Basic Accessibility Set Canceled',
		UAEyLkIF205:'Basic accessibility set has been activated',
		UAEyLkIF204:'Feedback - Your opinion is very important to us. In this tab you can contact us, provide feedback on the component, and recommend improvements.',
		UAEyLkIF203:'Help - Here you can find the accessibility statement and answers to frequently asked questions',
		UAEyLkIF202:'Personal Profile - In this tab you can save your accessibility settings, get recommendations and tips, and more.',
		UAEyLkIF201:'Main tab - Contains options for personalizing site accessibility. You have reached the UARttKAHhs display. You can navigate between the UARttKAHhs by right and left arrows. To enter the tab content click on the tab button',
		UAEyLkIF200:'You switch to the Accessibility menu',
		UAEyLkIF199:'The accessibility menu closed',
		UAEyLkIF198:'The accessibility menu opens',
		UAEyLkIF197:'Close pop-up settings',
		UAEyLkIF196:'Click to start the search',
		UAEyLkIF195:'The answer to this UAhMWTW is opend',
		UAEyLkIF194:'The answer to this UAhMWTW is hidden',
		UAEyLkIF193:'from',
		UAEyLkIF192:'Question',
		UAEyLkIF191:'New',
		UAEyLkIF190:'Reset text size',
		UAEyLkIF189:'Decrease and increase text',
		UAEyLkIF188:'Do you want to save thos setting or to update exiesting',
		UAEyLkIF187:'This option blocked.',
		UAEyLkIF186:'Yes, I"d love to finish',
		UAEyLkIF185:'Later',
		UAEyLkIF184:'2 more questions and the process of setting up your personal profile will end. What do you think, another little effort?',
		UAEyLkIF183:'Logout to andi',
		UAEyLkIF182:'login to andi',
		UAEyLkIF181:'This is a pop-up window, it is recommended to navigate with the tab button on the keyboard.',
		UAEyLkIF180:'Save my setting',
		UAEyLkIF179:'Cancel saving',
		UAEyLkIF178:'Want to keep the sequence of accessibility actions you"ve selected? Join our community and open a personal area',
		UAEyLkIF177:'Default color',
		UAEyLkIF176:'activated',
		UAEyLkIF175:'of',
		UAEyLkIF174:'Exact',
		UAEyLkIF173:'double',
		UAEyLkIF172:'1.5 rows',
		UAEyLkIF171:'Print to Braille',
		UAEyLkIF170:'Printing for vision impairment',
		UAEyLkIF169:' Pressing the right mouse button will show Accessibility menu',
		UAEyLkIF168:'A bottom menu opens to accompany you along the site',
		UAEyLkIF167:'When you enter the form field, the keyboard  will a appears',
		UAEyLkIF166:'Cancel',
		UAEyLkIF165:'Go to the next UAhMWTW',
		UAEyLkIF164:'Send',
		UAEyLkIF163:'send feedback',
		UAEyLkIF162:'The address of the page from which the email was sent:',
		UAEyLkIF161:'Please enter a valid email',
		UAEyLkIF160:'Email is required',
		UAEyLkIF159:'the form has been sent successfully',
		UAEyLkIF158:'Characters to type',
		UAEyLkIF157:'There are more',
		UAEyLkIF156:'NEXT',
		UAEyLkIF155:'Go to the next UAhMWTW',
		UAEyLkIF154:'PREVIOUS',
		UAEyLkIF153:'Return to previous UAhMWTW',
		UAEyLkIF152:'Your email',
		UAEyLkIF151:'Your first name',
		UAEyLkIF150:'Enter your details so we can get back to you',
		UAEyLkIF149:'Tell us more',
		UAEyLkIF148:'Did community recommendations helped you ?',
		UAEyLkIF147:'We"d love to knew how<br/>we can help more?',
		UAEyLkIF146:'No',
		UAEyLkIF145:'a little',
		UAEyLkIF144:'very',
		UAEyLkIF143:'Whether accessibility <br/>functions offered, have helped you ?',
		UAEyLkIF142:'Your answer will help us create a better experience',
		UAEyLkIF141:'We"d love to understand <br/>what makes it difficult to navigate and how we can improve it?',
		UAEyLkIF140:'Not at all',
		UAEyLkIF139:'medium',
		UAEyLkIF138:'Very Good',
		UAEyLkIF137:'How well you get along <br/> with the Andi navigation menu?',
		UAEyLkIF136:'Skip',
		UAEyLkIF135:'Skip this UAhMWTW.',
		UAEyLkIF134:'How well you get along with the Andi navigation menu?',
		UAEyLkIF133:"so we<br/> could really improve TUA's expirience ",
		UAEyLkIF132:'We will be glad if you are able to<br/> answer all of the questions ',
		UAEyLkIF131:'We would love a feedback',
		UAEyLkIF130:'Andy supports the leading browsers UAEIoBPet are: Chrome, Pierre Fox, Edge browser, Opera, Safari and Explorer 11.',
		UAEyLkIF129:'What browsers does Andy support?',
		UAEyLkIF128:'An accessibility ambassador is a surfer who invests his time in order to help other surfers. The help is provided by adding surfing recommendations according to the type of technology you are surfing with, and in return the accessibility ambassadors will be given various benefits from the publishers.',
		UAEyLkIF127:'What is Accessibility Ambassador?',
		UAEyLkIF126:'No. Andy remembers your usage settings with cookies, allowing you to customize accessibility once and enjoy browsing as you choose.',
		UAEyLkIF125:'If I did not keep my accessibility set, would I have to re-fit the page on every page',
		UAEyLkIF124:'Yes, you can save your accessibility adjustments accordingly. On the "Save" button you can save your selections UAEIoBPet will accompany you browsing any site where Andy appears. ',
		UAEyLkIF123:'Can I save my personal accessibility matches?',
		UAEyLkIF122:'Recommendations of the surfers community on how to surf the site in the most appropriate way according to the assistive technology (screen reader software, special accessories, accessibility keyboards).',
		UAEyLkIF121:'What does the community (people with disabilities) contribute to me? crowd wisdom',
		UAEyLkIF119:'Today Andi is the best technology in the web. Andi provides accessibility adjustments to all types of disabilities to the harshest level, whether you are blind or deaf You can always find the PIIs UAEIoBPet can help you make it easier for you to surf the web. Andi allows complete control over site visibility, content understanding, site navigation assistance Think about which technology uses keyboard or voice commands) and provides user feedback from the community by the wisdom of the masses UAEIoBPet consume Andy as a daily basis.',
		UAEyLkIF118:'Why Andi?',
		UAEyLkIF117:'You can join as an accessibility ambassador and earn various benefits from the various publishers',
		UAEyLkIF116:'Help other surfers by sharing your opinion on the nature of browsing the site with the help of Andi',
		UAEyLkIF115:'You can save different sets of accessibility of your choice',
		UAEyLkIF114:'User Guide',
		UAEyLkIF113:'Why should I register with you?',
		UAEyLkIF112:'Common questions',
		UAEyLkIF111:'Save my settting',
		UAEyLkIF110:'Reset all',
		UAEyLkIF109:'No explanation was found for the concept',
		UAEyLkIF108:'From the Wikipedia site',
		UAEyLkIF107:'You can see all entries matching Wikipedia on Wikipedia',
		UAEyLkIF106:'Loading finished',
		UAEyLkIF105:'There are several values that match the concept in Wikipedia:',
		UAEyLkIF104:'Loading information',
		UAEyLkIF103:'find Expression',
		UAEyLkIF102:'Look for phrases or concepts',
		UAEyLkIF101:'العربية',
		UAEyLkIF100:'עברית',
		/* Ver 1 text*/
		ANDItext103: 'You\'ve reached the button ',
		ANDItext102: 'You have reached the Select button ',
		ANDItext101: 'You\'ve reached a checkbox ' ,
		ANDItext100: 'You\'ve reached the field ',
		/* automation */
		UAeNXkpqs:'To the top of the page',
		UAKBYshutomationNextElm:'To Next item',
		UAKBYshutomationPrevElm:'To previous item',
		/* defined Checkbox */
		UACZoXZfXMark:'סומן',
		UAXNzWQWV:'לא סומן',
		/* hide Animate / flash */
		UAShONl:'Hide animation',
		UAShONl2:'Animation hidden',
		/* date piker */
		UAQesdYS:'Go to the next month',
		UAxNvpUncs:'Go to the previous month',
		/* Tabs */
		UAfFPXsLrQ:'Press Enter to enter the tab contents.',
		UAOsDwc:'Return to UARttKAHhs list.',
		UApHbIdPKO:'Finish navigating the UARttKAHhs and continuing navigation on the page.',
		/* light boxs */
		UAbnKLYRp: "You are about to exit the pop-up panel without closing it properly. If you want to close it now, press ESC on the keyboard. Know UAEIoBPet you may not be able to return to the panel. ",
		UAVrhGfv: "Pop-up window closed.",
		UAHWELiI: "Pop-up window starts. You can close and return to the previous page at any time by pressing ESC on the keyboard",
		/* menus */
		UAtUMZvHp:'Press to open a submenu',
		UAKTHtUMd:'Submenu opens',
		UAoZpsr:'Submenu closes',
		/* sliders & news */
		UAoUeDQojv: "Open Slider in a convenient navigation view ",
		UACTxnFH: "Return a standard display slider",
		UAMJZoio:"Easy navigation display slide",		
		UAeJOwTVXD: "Change display to easy view",
		UABOVWvx: "Return a news view to standard view",
		UAXDfQrKPn:"News view has been changed to a convenient view",
		UANuCAN: 'Display changed.',
		/* F A Q */
		UAhhBwV:'Open information regarding ',
		/* Breadcrumbs */
		UAdJTBijpd:'You are on the home page',
		UAcQsqFm :'In Category: ',
		UAhddzVqgA:'In an article called ',
		/* navigation search page */
		UAjSYLbd:'You are on page: ',
		UAdKEXoYe:'Page number : ',
		UArzREww:'Go to the first page ',
		UAlwhjGiO:'Go to last page',
		UAhmfZNc:'Go to  Next page',
		/* social network icons */
		UAxzyEaOZr:'Go to previous page',
		UAhEBYAuW:'To our facebook page',
		UAAMVrGAK:'To our Twitter',
		UAKylkoT:'To the YouTube channel',
		UAmAnNB:'Our address is in Waze',
		UAsiXNpN:'To our instagram',
		UAmPUDFt:'To our LinkedIn account',
		UAMgSOJzqh:'To our Google Plus account',
		UAZufyUD:'Send a message via your email software',
		/* validation forms */
		UAGTbZf:'Picture number ',
		UAPBbmPzh:'Do not use numbers',
		UAicyEs:'Please enter a valid date for example: 22/10/1979',
		UAdGAIXFCj:'You can close this message by pressing CTRL + Q on the keyboard',
		UAuLvHgtext:"This field can not be empty.",
		UAUdlhNOs:"This field can only contain numbers",
		UALqPfWtext: "Minimum characters must be entered: ",
		UApEdfRqcotext:"Maximum characters must be entered: ",
		UAMMhtntZCtext:"Please enter a valid email. for example: info@toovya.co.il",
		UAUuoKjlpo : 'The following errors were found:',
		UArmErA : 'בשדה ',
		/* download links */
		UArRzxJ:"Opens in a new window",
		UAkXUlyrm: "  File type PDF",
		UACxQZzqUo: "Simple text File type",
		UAoWtfBqp:"Word File type 	 ",
		UATMMpRc: "Excel File type  ",
		UAXdhIwRAW:"Presentation ",
		UAXZqoOT: "Image file",
		UAfwIwzL: "InDesign File type  ",
		UAhzfPYKPJ: "Illustrator File type  ",
		UATVKWA: "Photoshop file ",
		UAlAmwSaiy: "RAR File type  ",
		UAhWCqAM:"ZIP File type  ",
		UACtcUgfx:"JAR File type  ",
		UAnvPTPBCN: "ISO File type  ",
		UAwnLqZAb: "DMG File type  ",
		UAWUuyfq: "Audio file",
		UAWxRHq: "Video file",
		UAjqYuj:"Application file  ",
		UAatctvlHr: "VCD File type  ",
		UALUScXq:"ACEFile type  ",
		UANkkkng: "GZ File type  ",
        /* navigation with links */
        UAjaumOUw: "The beginning of a web page, press Enter to move to a central content",
        UAxlgiZFjU: " You can click Enter to return to the top of the page",
        UAmrcdlM: "You can press Enter to skip to the next area",
        UAVyKjGkf: 'You"ve reached the end of a page:',
        /* right mouse menu */
        UApjPqxYOj: "The mouse Help menu closes",
        UAkvtPnFT: "The mouse  menu opens",
        UAIymywt: "In the menu, you'll find the common actions and you can adjust the site for you. You can close this menu with the 'ESC' button on your keyboard",
        UAQoNNPMU: "Enable Magnifier mode for text.",
        UAOrPUo: "Save this page to your favorite list. ",
        UAqUhUlda: "Highlight the links with a bottom line",
        UARgFczYTR: "Change the background color to black with white text",
        UAoukRqN: "Change the background color to white with black text.",
        UAKqiPnV: "Return the site colors to their original color.",
        UAIRCOuT: "Change the font type to a more legible type.",
        UAcYxwU: "Increase the font.",
        UAWBjmuwqd: "Decrease the text.",
        UATVkqOoyx: "Resize the text to its original size. ",
        UAsEsDjma: "Browse to previous page.",
        UAJjRWRG: "Browse to the next page.",
        UAklpPbDEy: "Reload this page.",
        UAuBlFxK: "Copy the text you selected.",
        UAZXIslMvp: "Cut the text you selected.",
        UAGQKSZLa: "Paste the copied text.",
        UAsIBHMCP: "Paste",
        UARLeuw: "cut",
        UArNNlM: "copy",
        UAMNocksp: "Reload page",
        UAkGJnJLD: "Load Next page",
        UAbqgNe: "Load Previous Page",
	    /* accessibility menu */
	    UAPJTkiNI: '',
	    UAWOdaBbf: '',
	    UAeupFZVG: 'got it',
	    UAOQuqDs: 'By using TUA, you consent to use cookie files on your browser to improve our browsing experience.',
	    UAHsBiMowA: 'There are more functions enabled',
	    UAPZRyoFp: 'On the page',
	    UArkDuwAS: 'not found ',
	    UAbZUMII: 'Screen scrolling / marking of boxes in forms',
	    UAQJZUHl: 'Play',
	    UAEDTDkEPC: 'Opens the Accessibility Menu',
	    UAuFRcM: 'Go to URL bar',
	    UAfNpite: 'Refresh the page',
	    UATDdKo: 'Search',
	    UAjocGKmkD: 'Help',
	    UAmxNneXpE: 'Close / Cancel',
	    UAbYNQwxtt: 'image',
	    UASgJIdox: 'Move between images on a page',
	    UAvCYpXrDP: 'table',
	    UAWbCbmj: 'Move between tables on a page',
	    UAlXKUOOs: 'input',
	    UAGPdVUuc: 'Move between inputs on a page',
	    UAdOCTcqx: 'list item ',
	    UAEKuXy: 'Move between item in list on a page',
	    UAFWovtlTp: 'lists',
	    UADXJmuHZP: 'Move between lists on a page',
	    UAsKNFaQD: 'Links',
	    UAewRTo: 'Move between links on a page',
	    UAqgusemmj: 'Move between UANKaqLvcZ on a page',
	    UAoEyXRfmh: 'UANKaqLvcZ',
	    UAMTmLcFEf: 'Move between Headers on a page',
	    UAdcDJUEdf: 'Headers',
	    UAUDEGIe: 'Single',
	    UAfaXauh: 'Line spacing: 1.5',
	    UAMpFHa: 'Line spacing: Double',
	    UAoKuNTX: 'Line spacing: ',
	    UAMkMFdf: 'Letter spacing: ',
	    UAloBDZN: 'Word spacing: ',
	    UAreVWC: ' Turn off ',
	    UAapLYCnf: ' Finish ',
		UADBhyY:' Reset ',
	    UADKHhUMr: 'line spacing',
	    UACxAwykSE: 'Letters Spacing',
	    UAufcsthln: 'Words Spacing',
	    UALSmHEaV: 'Camera navigation',
	    UANdhlvaUj: 'Click for this message to no longer appear',
	    UAMkShSs: 'OK',
	    UALApwjC: 'right click on the mouse, a accessibility menu  will show.',
	    UAQQJyDoY: 'open the accessibility menu  from anywhere  Click F10',
	    UAqYPRR: 'Open Accessibility Menu',
	    UAoBqPTb: 'U.A - User accessibility Ltd &copy; 2018',
	    UAwHSPUODd: 'Devices Support ',
	    UANpeiGeb: 'Voice support',
	    UAJsCbfkn: 'Sign Language',
	    UATOItm: 'add	screen reader support',
	    UAKzAOSd: 'Navigate by letters',
	    UARsouDB: 'Highlight focus',
	    UAjsbhRNrE: 'VirUAEkKMFBEj keyboard',
	    UAlriVZm: 'Big white mouse',
	    UAUPSdw: 'Big black mouse',
	    UAyaknpATA: 'right click menu',
	    UAFFBWA: 'Adjust Navigation',
	    UACmrjuOdj: 'Color Adjust',
	    UAXwGUJbAs: 'Text color',
	    UAXBWkZ: 'Header color',
	    UAdTxZEIfq: 'Background color',
	    UARLwzZ: 'Dark background',
	    UACOarMij: 'Light background',
	    UAecihYq: 'Gray scale',
	    UABIRBUBMM: 'Adjust color contrast',
	    UAYcXizpkX: 'Content Assist',
	    UAMVxuquQ: 'show hidden info',
	    UApvwwT: 'Highlight Links',
	    UABetybFPO: 'Accessible printing',
	    UAuXMyv: 'Acronyms',
	    UAoptszs: 'Spotted text',
	    UAwrqLfw: 'Concepts and phrases',
	    UARZHANWc: 'Easy reading',
	    UAqnKoWTA: 'Target content area',
	    UAbedffJy: 'Help with content',
	    UACaNbuT: 'Text Adjust',
	    UAHbuupl: 'Align left',
	    UAvoCCkhZz: 'Align right',
	    UAQvwavhn: 'words Spacing',
	    UAbYxmQMJk: 'Spacing letters',
	    UARHByt: 'line spacing',
	    UABEponia: 'Readable font',
	    UAlcLrT: 'Increase text',
	    UAwkiOUX: 'Decrease text',
	    UAWfeucm: 'magnifying glass',
	    UAODNwlLY: 'Adjust text',
	    UAQmpfGsE:'Return to the previous screen',
	    UAtXeCcvUc:'Adjust the site for you',
	    UABSDebVi:'Set basic accessibility',
	    UAJkiEBUdsBtn:'Close the Accessibility menu',
        UATvARkBtn:'Increase the Accessibility menu',
        UAQwBTcCBtn:'Change the menu opening direction',
	    UAskDXZIYBtn:'Settings',
	    UABnRTCBEr:'feedback',
	    UAMUOBFimq:'Help',
        UALYouaeHa:'Profile',
        UAIyTEGxx:'Main',
		UAUGIEMTXU:  "טקסט חסר במערכת , בבקשה צור קשר עם המנהל"
	}
}