andiUA.UAeeQBQlu = function(){//'+andiUA.UAufVra.UAjBhsJJp2195+'
    
	return {
		UAjBhsJJp21961:'Continue',
		bbb144: 'You\'re in the Menu',
		bbb145: 'You\'re in the Top of Site',
		bbb146: 'You\'re in the Bottom of Site',
		Bbb147: 'You\'re in the main content area',
		bbb140:'close help',
		bbb141:'close help',
		bbb142:'print command',
		bbb143:'It is important to know: You can not operate with voice commands browser warnings.',
		bbb139:'You have turned off voice commands.',
		bbb138:'Voice commands have been activated. We will open a popup containing the list of commands.',
		bbb137:'Web page navigation',
		bbb136:'General operation on the web page',
        bbb135:'Print list of voice commands',
        bbb134:'List of voise commands',
        bbb133:'Add new word for this command',
        bbb132:'Enable / Disable Content Area Targeting',
        bbb131:'Show help',
        bbb130: 'Enable / Disable text alignment to the left', 
        bbb129: 'Enable / Disable text alignment to the right',
        bbb128: 'Scroll down page',
        bbb127: 'Scroll Page Up',
        bbb126: 'To previous heading',
        bbb125: 'To the next heading',
        bbb124: 'To the previous input field',
        bbb123: 'To the next input field',
        bbb122: 'To the previous button',
        bbb121: 'Next button', 
        bbb120: 'To the previous link',
        bbb119: 'Next Link',
        bbb118: 'To previous link',
        bbb117: 'Next Link',
        bbb116: 'Reload this page',
        bbb115: 'Reset all menu settings',
        bbb113: 'On / Off to change the cursor to white big mouse cursor ',
        bbb112: 'On / Off to change the cursor to black big mouse cursor',
        bbb111: 'on / off highlight focus',
        bbb110: 'Show virUARlAcVM keyboard',
        bbb109: 'Close VirUARlAcVM Keyboard',
        bbb108: 'Enable / Disable change font to Ariel',
        bbb107: 'On / Off page reading',
        bbb106: 'Close page summary',
        bbb105: 'Show page summary',
        bbb104: 'Enable / Disable Initials',
        bbb103: 'Turn all animation on / off',
        bbb102: 'Enable / disable dark contrast mode',
        bbb101: 'Enable / Disable Bright Contrast Mode',
        bbb100: 'On / Off highlighting links',
        bbb99: 'Enable Print Accessibility',
        bbb98: 'Turning off concepts and phrases',
        bbb97: 'Enabling concepts and phrases',
        bbb96: 'Turn Magnifier On / Off',
        bbb95: 'Reset Text Size',
        bbb94: 'Decreases text',
        bbb93: 'enlarges the text',
        bbb92: 'Closes accessibility menu',
        bbb91: 'Opens / closes the accessibility menu',
        bbb90: 'Opens / closes the accessibility menu',
        bbb89: 'Deletes all text within input field', 
        bbb88: 'Emulates the left mouse button or ENTER button',
        bbb87: 'Load the next page you\'ve browsed to',
        bbb86: 'Load the previous page you browsed to',
        bbb85:'note',
        bbb84:'Add a new Voice command to this command',
        bbb83:'explanation',
        bbb82:'(Voice command)',
        bbb81:'page down',
        bbb80:'page Up',
        bbb79:'back heading',
        bbb78:'heading',
        bbb77:'back input',
        bbb76:'input',
        bbb75:'back button',
        bbb74:'button',
        bbb73:'backlink',
        bbb72:'nextlink',
        bbb71:'back link',
        bbb70:'link',
        bbb69:'reload page',
        bbb68:'reset all option',
        bbb67:'white Mouse',
        bbb66:'black Mouse',
        bbb65:'Highlight focus',
        bbb64:'virUARlAcVM keyboard',
        bbb63:'close virUARlAcVM keyboard',
        bbb62:'ariel',
        bbb61:'Read content',
        bbb60:'close summary',
        bbb59:'show summary',
        bbb58:'rashe Tevot',
        bbb57:'Stop all movement',
        bbb56:'Dark background',
        bbb55:'Light background',
        bbb54:'Highlight Links',
        bbb53:'Accessible printing',
        bbb52:'close Concept',
        bbb51:'Concept',
        bbb50:'Target content area',
        bbb49:'Magnifying Glass',
        bbb48:'align Left',
        bbb47:'align Right',
        bbb46:'reset text',
        bbb45:'small text',
        bbb44:'big text',
        bbb43:'close',
        bbb42:'open',
        bbb41:'andy',
        bbb40:'delete all text',
        bbb39:'click',
        bbb38:'next page',
        bbb37:'last page',
        bbb36:'help',
        bbb35: 'You have skip thos links. Continue Navigate the site.',
        bbb34: ' links, Do you want to skip on it? Press ENTER if yes.',
        bbb33: 'In this area have ',
        bbb32: 'High contrast mode within the menu is activated',
        bbb31: 'High contrast mode within the menu is canceled',
        bbb30: 'Change menu colors to high contrast colors',
        bbb29: 'High contrast',
        bbb28: 'Page summary has been disabled',
        bbb27: 'A summary of the page is displayed, in the transition between the pages of the site, at the end of each page there is a button that will be displayed on the page summary',
        bbb26: 'Displays summary',
        bbb25: 'Run forward reading',
        bbb24: 'Run backward reading',
        bbb23: 'Pause reading',
        bbb22: 'Start reading, with a click you go to a pop-up pane that show all the text that will read',
        bbb21: 'A playback panel opens, the focus now moving to it',
        bbb20: 'Play panel closed',
        bbb19: 'Read content',
        bbb18: 'Page navigation menu',
        bbb17: 'Page number ',
        bbb16: 'The products in the shopping cart are: ',
        bbb15: 'Products in a shopping cart',
        bbb14: 'The page will be reloaded and will also disable bold focus and bold links. Are you sure? ',
        bbb13: 'Common questions',
        bbb1: "The accessibility plugin Andi has detected new content on the page you're browsing.",
        bbb2: 'Do you want us to make the new content on this site accessibile?',
        bbb3: 'Yes, make the new content on this site accessibile.',
        bbb7: 'Ask me again in 5 minutes.',
        bbb4: 'Ask me next browsing.',
        bbb12: 'Choose the right option for you.',
        bbb11: 'PopUp Window - loading new content',
        bbb8: 'Your selection has been made. As long as you do not close the pop-up panel, you can change the selection.',
        bbb9: 'The popup panel closes without selecting anything, it will reappear in next browsing session. You are returned to where you were on the page.',
        bbb10: 'The Popup panel is closed and you are returned to where you were on the page.',
        bbb5: 'Do not make the new content on this site accessibile.',
        bbb6: 'continue',
        UAjBhsJJp2200: "",
        UAjBhsJJp2199: "",
        UAjBhsJJp2198: "",
        UAjBhsJJp2197: "",
        UAjBhsJJp2196: "Use the up and down arrows to change the spacing",
        UAjBhsJJp2195: "Press SPACE to write",
        UAjBhsJJp2194: "(Close by CTRL + Q)",
        UAjBhsJJp2193: "Close navigation with letter",
        UAjBhsJJp21931: 'Hello,<br/>There is a new version. To enjoy the many new features you need to update a version: <a style="color:#FFFF00 !important;text-decoration: underline !important;" target="_blank" href="https://chrome.google.com/webstore/detail/andi-on/jbcpiombjbhkdngdjfbidgdihfobcaaa" >You can find it here</a>',
        UAjBhsJJp2192: "This option is disabled in IE",
        UAhKbUwreadcrumb1: "You are on the page ",
        UAhKbUwreadcrumb2: "category ",
        UAhKbUwreadcrumb3: "In category ",
        UAjBhsJJp2191: "You have return to main screen",
        UAjBhsJJp2190: "Tab content ready",
        UAjBhsJJp2189: "Sponsored by ",
        UAjBhsJJp2188: "Close search Results",
        UAjBhsJJp2187: "From Wikipedia site",
        UAjBhsJJp2186: 'Activating this function may cause flickering on the screen of your computer. Pressing the "OK" button will activate the function.If you are sensitive to flickering - do not activate this function and press the "Cancel" button.',
        UAjBhsJJp2185: "Cookies policy",
        UAjBhsJJp2184: "Privacy Policy",
        UAjBhsJJp2183: "To reset the site colors, the page will be reloaded",
        UAjBhsJJp2182: "Accessible print mode",
        UAjBhsJJp2181: "To easily search for concepts and phrases, the accessibility menu will now close.",
        UAjBhsJJp2180: "Highlighting for links canceled",
        UAjBhsJJp2179: "All links were highlighted with underlined",
        UAjBhsJJp2178: "The menu moved to the other side ",
        UAjBhsJJp2177: "The menu size return to nurmal",
        UAjBhsJJp2176: "The menu size is now bigger",
        UAjBhsJJp2175: " User Guide , will open in new window",
        UAjBhsJJp2174: "Color Selection menu",
        UAjBhsJJp2173: "Click to close the Color Selection menu",
        UAjBhsJJp2172: "The amount of spacing you want to set between text lines",
        UAjBhsJJp2171: "The Language Selection menu closes",
        UAjBhsJJp2170: "Continue navigating with the tab button to reach the save button.",
        UAjBhsJJp2169: "The Settings menu opens",
        UAjBhsJJp2168: "The Settings menu closes",
        UAjBhsJJp2167: "Continue navigating to hear and select accessibility options",
        UAjBhsJJp2166: "Menu opens",
        UAjBhsJJp2165: "After clicking, you will focus on the right Panel",
        UAjBhsJJp2164: "Close the preview message screen",
        UAjBhsJJp2163: "Accessibility Statement",
        UAjBhsJJp2162: "This option can not be enabled on smartphones and tablets",
        UAjBhsJJp2161: "Open menu in accessible mode (menu will open in pop-up panel)",
        UAjBhsJJp2160: "All links in the menu",
        UASQAKZENY: "Close pop-up",
        UApetWnQWt: "Pop-up pane has been closed.",
        UAGOGSZ: "The beginning of a web page, click to go to the main content",
        UAjBhsJJp2159: "close this message",
        UAjBhsJJp2158: 'To activate navigation by keyboard press the <span style="border: 1px solid #fff !important;" id="UAbNOvFF" role="button" tabindex="0"> Y key</span> Know that you can always enable this option through the accessibility menu',
        UAjBhsJJp2157: "Saved successfully",
        UAjBhsJJp2156: "The set: ",
        UAjBhsJJp2155: "Name the adjustments you made",
        UAjBhsJJp2154: 'Language selected, proceed to "Change Language" button to apply the change.',
        UAjBhsJJp2153: "This language is the current language",
        UAjBhsJJp2152: "Change language (page will reload)",
        UAjBhsJJp2151: "Soon",
        UAjBhsJJp2150: "Menu language. When clicked will go to a menu that displays the languages to select for the interface. After selecting the language, navigate to the end of the list to the 'Update Language' button. Note that the page will reload.",
        UAjBhsJJp2149: "Connected",
        UAjBhsJJp2148: "Menu language",
        UAjBhsJJp2147: "Turn off Addon on this site",
        UAjBhsJJp2146: "The team behind ANDI",
        UAjBhsJJp2145: "Usage Policy",
        UAjBhsJJp2144: "You are not logged in to your account in the accessibility plugin - Andi On",
        UAjBhsJJp2143: "Log out from your account",
        UAjBhsJJp2142: "Log in to your account",
        UAjBhsJJp2141: "Log out",
        UAjBhsJJp2140: "Log in",
        UAjBhsJJp2139: "I agree to these terms and also understand that when choosing a language the interface may be reloaded",
        UAjBhsJJp2138: "Open the main accessibility menu from anywhere on the site and press F10",
        UAjBhsJJp2137: "I agree to the terms",
        UAjBhsJJp2136: "More information on our use regulations.",
        UAjBhsJJp2135: "To improve your browsing experience with the extension, we use cookies. By using the AddOn you agree to the use of cookies.",
        UAjBhsJJp2134: "My preferred menu language is",
        UAjBhsJJp2133: "Some adjustments before starting",
        UAjBhsJJp2132: "F - Skip between input fields. ( If the input field is an editing field where you can enter text, this interface will be automatically disabled to allow you to type ).",
        UAjBhsJJp2131: "B - Skip between buttons",
        UAjBhsJJp2130: "G - Skip between images",
        UAjBhsJJp2129: "H - Skip between titles",
        UAjBhsJJp2128: "T - Skip between tables",
        UAjBhsJJp2127: "K - Skip between links",
        UAjBhsJJp2126: "I - Skip between items in the list",
        UAjBhsJJp2125: "L - Skip between lists",
        UAjBhsJJp2124: "By tapping one of the following letters you can easily skip between:",
        UAjBhsJJp2123: "With the new interface we developed, you can now navigate by the type of information you're looking for.",
        UAjBhsJJp2122: "I got it, do not show me any more",
        UAjBhsJJp2121: "Reset languages",
        UAjBhsJJp2120: "Change language",
        UAjBhsJJp2119: "Select the interface language",
        UAjBhsJJp2118: "For the following reason:",
        UAjBhsJJp2117: "User has turned off the extension on the following site",
        UAjBhsJJp2116: "The user did not specify why",
        UAjBhsJJp2115: "Turn off, the page will reload",
        UAjBhsJJp2114: "The reason I close this Addon is:",
        UAjBhsJJp2113: "The plugin does not give me the accessibility I need",
        UAjBhsJJp2112: "The plugin slows the site",
        UAjBhsJJp2111: "The plugin breaks the site",
        UAjBhsJJp2110: "It's important for us to know why you do not want the extension to run on this site",
        UAjBhsJJp2109: "Don't make this site accessible",
        UAjBhsJJp2108: "For example, high contrast adjust",
        UAjBhsJJp2107: "Close pop-up",
        UAjBhsJJp2106: "All animations Disabled",
        UAjBhsJJp2105: "GIF animations Disabled",
        UAjBhsJJp2104: "Stop all movement",
        UAjBhsJJp2103: "The page will refresh to restore animations",
        UAjBhsJJp2102: "Stop GIF animations",
        UAjBhsJJp2101: "Advanced support for screen reader software has been canceled, the page will be reloaded.",
        UAjBhsJJp2100: "Advanced screen reader support has been enabled",
        UAjBhsJJp299: "Update exiesting set",
        UAjBhsJJp298: "Save new set",
        UAjBhsJJp297: "Area number",
        UAjBhsJJp296: "You must enter a search term or phrase",
        UAjBhsJJp295: "You can drag the button anywhere with your mouse or move it with your keyboard arrows",
        UAjBhsJJp294: "Dark gray color",
        UAjBhsJJp293: "Light gray color",
        UAjBhsJJp292: "Brown color",
        UAjBhsJJp291: "Dark orange color",
        UAjBhsJJp290: "Magenta pink color",
        UAjBhsJJp289: "Light orange color",
        UAjBhsJJp288: "yellow color",
        UAjBhsJJp287: "Light green color",
        UAjBhsJJp286: "Dark green color",
        UAjBhsJJp285: "Turquoise color",
        UAjBhsJJp284: "blue color",
        UAjBhsJJp283: "purple color",
        UAjBhsJJp282: "pink color",
        UAjBhsJJp281: "Red color",
        UAjBhsJJp280: "White color",
        UAjBhsJJp279: "Backward",
        UAjBhsJJp278: "Reset",
        UAjBhsJJp277: "Reset all settings in this category",
        UAjBhsJJp276: "By pressing the button, basic accessibility will be activated:&#xa;1. Enlargement of text &#xa;2.  Changing the font type to more readable font&#xa;3. Links will have a bottom line added&#xa;4. The mouse cursor will grow",
        UAjBhsJJp275: "You can choose what to do: &#xa; 1. Make accessibility adjustments.&#xa;2. Take actions on your personal account &#xa; 3. Learn about Andi with our guide. Send us feedback about Andi, and report problems. &#xa;&#xa; You can switch between topics using the right and left arrows. To access the content, click the tab button on your keyboard. ",
        UAjBhsJJp274: "Click to find out more options for customizing a site for you. &#xa; You can increase text, change spacing, select colors, search for concepts, enjoy accessible printing and much more.",
        UAjBhsJJp273: "Close the menu",
        UAjBhsJJp272: "Change direction",
        UAjBhsJJp271: "Increase the menu",
        UAjBhsJJp270: "Show this advertisement in an accessible format",
        UAjBhsJJp269: "Back to image",
        UAjBhsJJp268: "Live text",
        UAjBhsJJp267: "Seconds",
        UAjBhsJJp266: "Close this advertisement",
        UAjBhsJJp265: "Close this advertisement in",
        UAjBhsJJp264: "Close help",
        UAjBhsJJp263: "Close help in",
        UAjBhsJJp262: "This button changes the opening direction of the menu. Try now",
        UAjBhsJJp261: "This button increases the menu for convenient and easy viewing. Try now",
        UAZJSfn: "Your request is done",
        UAzFzBUnWV: "Starts Making your request",
        UAUQzcH: "Loading data from server",
        UAjBhsJJp257: "Accessibility is ready",
        UAjBhsJJp256: "Starts loading accessibility",
        UAjBhsJJp255: "Reset all settings ? \n The page will reload.",
        UAjBhsJJp254: "Sub menu settings has been closed",
        UAjBhsJJp253: "Region targeting was canceled",
        UAjBhsJJp252: "Focus mode Region activated",
        UAjBhsJJp251: "Canceled status and the page will be reloaded.",
        UAjBhsJJp250: "All initials have been changed to full text",
        UAjBhsJJp249: "An accessible print preview window opens",
        UAjBhsJJp248: "A search box opens for Wikipedia concepts, the accessibility menu is now closed and you move to the search box that opens",
        UAjBhsJJp247: "A hidden information state has been canceled",
        UAjBhsJJp246: "Hidden information mode is displayed in visible mode",
        UAjBhsJJp245: "VirUARlAcVM keyboard canceled",
        UAjBhsJJp244: "VirUARlAcVM keyboard enabled",
        UAjBhsJJp243: "Focus Bold was canceled",
        UAjBhsJJp242: "Focus Bold was activated",
        UAjBhsJJp241: "The mouse cursor has returned to its original size",
        UAjBhsJJp240: "The mouse cursor was enlarged and painted white",
        UAjBhsJJp239: "The mouse cursor was enlarged and painted black",
        UAjBhsJJp238: "Navigate with is letters canceled ",
        UAjBhsJJp237: "Navigate with is letters activated ",
        UAjBhsJJp236: "Font change mode canceled",
        UAjBhsJJp235: "Font type changed to Ariel",
        UAjBhsJJp234: "The site has returned to normal",
        UAjBhsJJp233: "The site is different to grayscale",
        UAjBhsJJp232: "Bright contrast mode was canceled",
        UAjBhsJJp231: "Bright contrast mode was activated",
        UAjBhsJJp230: "Dark contrast mode was canceled",
        UAjBhsJJp229: "Dark contrast mode was activated",
        UAjBhsJJp228: "Background color canceled",
        UAjBhsJJp227: "The colors you chose were saved",
        UAjBhsJJp226: "Background color reset",
        UAjBhsJJp225: "Background color changed",
        UAjBhsJJp224: "Header color and links reset",
        UAjBhsJJp223: "Headers and links color changed",
        UAjBhsJJp222: "Text color reset",
        UAjBhsJJp221: "Text color changed",
        UAjBhsJJp220: "All text alignments have been returned to normal",
        UAjBhsJJp219: "Text aligned to right",
        UAjBhsJJp218: "Text is left-aligned",
        UAjBhsJJp217: "The text returned to its original size",
        UAjBhsJJp216: "Text has been reduced",
        UAjBhsJJp215: "Text increased",
        UAjBhsJJp214: "Magnifying glass stopped",
        UAjBhsJJp213: "Magnifier activated",
        UAjBhsJJp212: "Adjusting to navigational - Pressing the button will open a menu containing settings for this category ",
        UAjBhsJJp211: "djusting color contrast - Pressing the button will open a menu containing settings for this category",
        UAjBhsJJp210: "Help with understanding the content - clicking the button will open a menu UARjBTbqt contains settings for this category",
        UAjBhsJJp209: "Adjust text visibility - Clicking the button will open a menu containing settings for this category",
        UAjBhsJJp208: "Save and open a personal area - Once you click, you will go to a personal profile and you can save your settings",
        UAjBhsJJp207: "All settings have been reset",
        UAjBhsJJp206: "Basic Accessibility Set Canceled",
        UAjBhsJJp205: "Basic accessibility set has been activated",
        UAjBhsJJp204: "Feedback - Your opinion is very important to us. In this link you can contact us, provide feedback on the component, and recommend improvements.",
        UAjBhsJJp203: "Help - Here you can find the User Guide and answers to frequently asked questions",
        UAjBhsJJp202: "Personal Profile - In this link you can save your accessibility settings, get recommendations and tips, and more.",
        UAjBhsJJp201: "Main panel - Contains options for personalizing site accessibility. To enter click Enter.",
        UAjBhsJJp200: "You switch to the Accessibility menu",
        UAjBhsJJp199: "The accessibility menu closed",
        UAjBhsJJp198: "The accessibility menu opens, you need navigate the menu using the TAB button",
        UAjBhsJJp197: "Close pop-up settings",
        UAjBhsJJp196: "Click to start the search",
        UAjBhsJJp195: "The answer to this UAzZvjf is opend",
        UAjBhsJJp194: "The answer to this UAzZvjf is hidden",
        UAjBhsJJp193: "from",
        UAjBhsJJp192: "Question",
        UAjBhsJJp191: "New",
        UAjBhsJJp190: "Reset text size",
        UAjBhsJJp189: "Decrease and increase text",
        UAjBhsJJp188: "Do you want to save thos setting or to update exiesting",
        UAjBhsJJp187: "This option blocked.",
        UAjBhsJJp186: 'Yes, I"d love to finish',
        UAjBhsJJp185: "Later",
        UAjBhsJJp184: "2 more questions and the process of setting up your personal profile will end. What do you think, another little effort?",
        UAjBhsJJp183: "Logout to andi",
        UAjBhsJJp182: "login to andi",
        UAjBhsJJp181: "This is a pop-up window, it is recommended to navigate with the tab button on the keyboard.",
        UAjBhsJJp180: "Save my setting",
        UAjBhsJJp179: "Cancel saving",
        UAjBhsJJp178: 'Want to keep the sequence of accessibility actions you"ve selected? Join our community and open a personal area',
        UAjBhsJJp177: "Default color",
        UAjBhsJJp176: "activated",
        UAjBhsJJp175: "of",
        UAjBhsJJp174: "Exact",
        UAjBhsJJp173: "double",
        UAjBhsJJp172: "1.5 rows",
        UAjBhsJJp171: "Print to Braille",
        UAjBhsJJp170: "Printing for vision impairment",
        UAjBhsJJp169: " Pressing the right mouse button will show Accessibility menu",
        UAjBhsJJp168: "A new menu opens and will accompany you along the site. Now the accessibility menu closes and you go to the menu that opens",
        UAjBhsJJp167: "When you enter the form field, the keyboard  will a appears",
        UAjBhsJJp166: "Cancel",
        UAjBhsJJp165: "Go to the next UAzZvjf",
        UAjBhsJJp164: "Send",
        UAjBhsJJp163: "send feedback",
        UAjBhsJJp162: "The address of the page from which the email was sent:",
        UAjBhsJJp161: "Please enter a valid email",
        UAjBhsJJp160: "Email is required",
        UAjBhsJJp159: "the form has been sent successfully",
        UAjBhsJJp158: "Characters to type",
        UAjBhsJJp157: "There are more",
        UAjBhsJJp156: "NEXT",
        UAjBhsJJp155: "Go to the next UAzZvjf",
        UAjBhsJJp154: "PREVIOUS",
        UAjBhsJJp153: "Return to previous UAzZvjf",
        UAjBhsJJp152: "Your email",
        UAjBhsJJp151: "Your first name",
        UAjBhsJJp150: "Enter your details so we can get back to you",
        UAjBhsJJp149: "Tell us more",
        UAjBhsJJp148: "Did community recommendations helped you ?",
        UAjBhsJJp147: 'We"d love to knew how<br/>we can help more?',
        UAjBhsJJp146: "No",
        UAjBhsJJp145: "a little",
        UAjBhsJJp144: "very",
        UAjBhsJJp143: "Whether accessibility <br/>functions offered, have helped you ?",
        UAjBhsJJp142: "Your answer will help us create a better experience",
        UAjBhsJJp141: 'We"d love to understand <br/>what makes it difficult to navigate and how we can improve it?',
        UAjBhsJJp140: "Not at all",
        UAjBhsJJp139: "medium",
        UAjBhsJJp138: "Very Good",
        UAjBhsJJp137: "How well you get along <br/> with the Andi navigation menu?",
        UAjBhsJJp136: "Skip",
        UAjBhsJJp135: "Skip this UAzZvjf.",
        UAjBhsJJp134: "How well you get along with the Andi navigation menu?",
        UAjBhsJJp133: "so we<br/> could really improve TUA's expirience ",
        UAjBhsJJp132: "We will be glad if you are able to<br/> answer all of the questions ",
        UAjBhsJJp131: "We would love a feedback",
        UAjBhsJJp130: "Andi supports the leading browsers UARjBTbqt are: Chrome, Pierre Fox, Edge browser, Opera, Safari and Explorer 11.",
        UAjBhsJJp129: "What browsers does Andi support?",
        UAjBhsJJp128: "An accessibility ambassador is a surfer who invests his time in order to help other surfers. The help is provided by adding surfing recommendations according to the type of technology you are surfing with, and in return the accessibility ambassadors will be given various benefits from the publishers.",
        UAjBhsJJp127: "What is Accessibility Ambassador?",
        UAjBhsJJp126: "No. Andi remembers your usage settings with cookies, allowing you to customize accessibility once and enjoy browsing as you choose.",
        UAjBhsJJp125: "If I did not keep my accessibility set, would I have to re-fit the page on every page",
        UAjBhsJJp124: 'Yes, you can save your accessibility adjustments accordingly. On the "Save" button you can save your selections UARjBTbqt will accompany you browsing any site where Andi appears. ',
        UAjBhsJJp123: "Can I save my personal accessibility UAwgmOsu?",
        UAjBhsJJp122: "Recommendations of the surfers community on how to surf the site in the most appropriate way according to the assistive technology (screen reader software, special accessories, accessibility keyboards).",
        UAjBhsJJp121: "What does the community (people with disabilities) contribute to me? crowd wisdom",
        UAjBhsJJp119: "Today Andi is the best technology in the web. Andi provides accessibility adjustments to all types of disabilities to the harshest level, whether you are blind or deaf You can always find the PIIs UARjBTbqt can help you make it easier for you to surf the web. Andi allows complete control over site visibility, content understanding, site navigation assistance Think about which technology uses keyboard or voice commands) and provides user feedback from the community by the wisdom of the masses UARjBTbqt consume Andi as a daily basis.",
        UAjBhsJJp118: "Why Andi?",
        UAjBhsJJp117: "You can join as an accessibility ambassador and earn various benefits from the various publishers",
        UAjBhsJJp116: "Help other surfers by sharing your opinion on the nature of browsing the site with the help of Andi",
        UAjBhsJJp115: "You can save different sets of accessibility of your choice",
        UAjBhsJJp114: "User Guide",
        UAjBhsJJp113: "Why should I register with you?",
        UAjBhsJJp112: "Common questions",
        UAjBhsJJp111: "Save my settting",
        UAjBhsJJp110: "Reset all",
        UAjBhsJJp109: "No explanation was found for the concept",
        UAjBhsJJp108: "From the Wikipedia site",
        UAjBhsJJp107: "You can see all entries matching Wikipedia on Wikipedia",
        UAjBhsJJp106: "Loading finished",
        UAjBhsJJp105: "There are several UAvWyVk that match the concept in Wikipedia:",
        UAjBhsJJp104: "Loading information",
        UAjBhsJJp103: "find Expression",
        UAjBhsJJp102: "Look for phrases or concepts",
        UAjBhsJJp101: "\u0627\u0644\u0639\u0631\u0628\u064a\u0629",
        UAjBhsJJp100: "\u05e2\u05d1\u05e8\u05d9\u05ea",
        ANDItext103: "You've reached the button ",
        ANDItext102: "You have reached the Select button ",
        ANDItext101: "You've reached a checkbox ",
        ANDItext100: "You've reached the field ",
        UANyVsh: "To the top of the page",
        UAdNQlyAutomationNextElm: "To Next item",
        UAdNQlyAutomationPrevElm: "To previous item",
        UAaomEfHMark: "\u05e1\u05d5\u05de\u05df",
        UASziYzS: "\u05dc\u05d0 \u05e1\u05d5\u05de\u05df",
        UAJlUxRiu: "Hide animation",
        UAJlUxRiu2: "Animation hidden",
        UAJYKPzT: "Go to the next month",
        UAuIQDQw: "Go to the previous month",
        UACyeDenp: "Press Enter to enter the tab contents.",
        UAGcrcix: "Return to UAYxugGs list.",
        UAxUASKWC: "Finish navigating the UAYxugGs and continuing navigation on the page.",
        UAREmzKttf: "You are about to exit the pop-up panel without closing it properly. If you want to close it now, press ESC on the keyboard. Know UARjBTbqt you may not be able to return to the panel. ",
        UAziozB: "Pop-up window starts. You can close and return to the previous page at any time by pressing ESC on the keyboard",
        UAuDTPt: "Press to open a submenu",
        UAvXFpnXI: "Submenu opens",
        UAjaWeodRj: "Submenu closes",
        UAmKDEwwF: "Open Slider in a convenient navigation view ",
        UAkBRvS: "Return a standard display slider",
        UAjTaHg: "Easy navigation display slide",
        UAWqzEjTt: "Change display to easy view",
        UADrTpo: "Return a news view to standard view",
        UAHatjiUB: "News view has been changed to a convenient view",
        UApDTtoxiN: "Display changed.",
        UAAxstbj: "Open information regarding ",
        UAlguKYy: "You are on the home page",
        UAgGLkVUUM: "In Category: ",
        UAYawxGHNm: "In an article called ",
        UAYBaxdb: "You are on page: ",
        UAknvreif: "Page number : ",
        UAUWumMj: "Go to the first page ",
        UAjHbGyd: "Go to last page",
        UAXHAKn: "Go to  Next page",
        UAaxkrl: "Go to previous page",
        UAzgQTb: "To our facebook page",
        UAWDVKILFT: "To our Twitter",
        UAAylbeIHd: "To the YouTube channel",
        UAZMezwdFv: "Our address is in Waze",
        UAIbhCMnw: "To our instagram",
        UAjWkwAJ: "To our LinkedIn account",
        UARiondqvO: "To our Google Plus account",
        UAYMnUG: "Send a message via your email software",
        UALlwbRSi: "Picture number ",
        UAUAcJNot: "Do not use numbers",
        UAUWqlNhFF: "Please enter a valid date for example: 22/10/1979",
        UAUVBMewH: "You can close this message by pressing CTRL + Q on the keyboard",
        UAFUHInadF: "This field can not be empty.",
        UAdFptRaJz: "This field can only contain numbers",
        UAtCjyFKPd: "Minimum characters must be entered: ",
        UAFCCCl: "Maximum characters must be entered: ",
        UAMVbDoCEz: "Please enter a valid email. for example: info@toovya.co.il",
        UAjIndTEx: "The following errors were found:",
        UAJExBEz: "\u05d1\u05e9\u05d3\u05d4 ",
        UABRfSutY: "Opens in a new window",
        UAMAlfLN: "  File type PDF",
        UAmMcJFN: "Simple text File type",
        UAakUWFgY: "Word File type \t ",
        UAvQyPkW: "Excel File type  ",
        UAMhEUCKP: "Presentation ",
        UAhKxfVXfj: "Image file",
        UAIwgSZ: "InDesign File type  ",
        UAiIKoF: "Illustrator File type  ",
        UAxabSCDZP: "Photoshop file ",
        UAnrCCm: "RAR File type  ",
        UAqYMXH: "ZIP File type  ",
        UAVaNZGp: "JAR File type  ",
        UAhaqNx: "ISO File type  ",
        UAmupcNI: "DMG File type  ",
        UAXqBlWxxP: "Audio file",
        UAwDynreCo: "Video file",
        UAnDREvw: "Application file  ",
        UAjrkXM: "VCD File type  ",
        UACNWfSwq: "ACEFile type  ",
        UAwmRsObxi: "GZ File type  ",
        UAXspWxX: " You can click Enter to return to the top of the page",
        UAultLFP: "You can press Enter to skip to the next area",
        UALYzyJ: 'You"ve reached the end of a page:',
        UARNWgVZKr: "The mouse Help menu closes",
        UAGrOykR: "The mouse  menu opens",
        UApnbExum: "In the menu, you'll find the common actions and you can adjust the site for you. You can close this menu with the 'ESC' button on your keyboard",
        UAcCyfEfT: "Enable Magnifier mode for text.",
        UABDhuUAD: "Save this page to your favorite list. ",
        UACqMue: "Highlight the links with a bottom line",
        UAdxRXPWVL: "Change the background color to black with white text",
        UAoluzK: "Change the background color to white with black text.",
        UAcgxSPIYk: "Return the site colors to their original color.",
        UAFLONeVU: "Change the font type to a more legible type.",
        UAwYGkte: "Increase the font.",
        UAKbfilc: "Decrease the text.",
        UApxLqQB: "Resize the text to its original size. ",
        UAskaRhppu: "Browse to previous page.",
        UALnOaQD: "Browse to the next page.",
        UAZfFLeZ: "Reload this page.",
        UAdjDRTr: "Copy the text you selected.",
        UAXqonwSbE: "Cut the text you selected.",
        UAaQhpFRn: "Paste the copied text.",
        UAxaIsSAYn: "Paste",
        UArHDrysqC: "cut",
        UADplXHTox: "copy",
        UAlJvrd: "Reload page",
        UAeHIAY: "Load Next page",
        UAaqpDwyIY: "Load Previous Page",
        UAqEgpUpfd: "",
        UACdZgCrIn: "",
        UAYrozqIcd: "got it",
        UAVacptNpJ: "By using TUA, you consent to use cookie files on your browser to improve our browsing experience.",
        UALGDvXWG: "There are more functions enabled",
        UAonUez: "On the page",
        UANXTNhlj: "not found ",
        UAmAlSI: "Screen scrolling / marking of boxes in forms",
        UASUypJ: "Play",
        UAgshhXGa: "Opens the Accessibility Menu",
        UAsTidMA: "Go to URL bar",
        UAQnvHQZA: "Refresh the page",
        UASAuaLN: "Search",
        UAHlMpkuh: "Help",
        UAfwbyjRR: "Close / Cancel",
        UAqfIXMmKr: "image",
        UAqgzQm: "Move between images on a page",
        UADZHxecF: "table",
        UANEuOfaMK: "Move between tables on a page",
        UAfEUqZU: "input",
        UAJrFfxyb: "Move between inputs on a page",
        UArQSOdU: "list item ",
        UATMxsM: "Move between item in list on a page",
        UAhqOxWZ: "lists",
        UAKvGRMcF: "Move between lists on a page",
        UAfJyUfjgH: "Links",
        UAihdvUnG: "Move between links on a page",
        UAJjpnA: "Move between UAoYbZEFQ on a page",
        UABIyLl: "UAoYbZEFQ",
        UADfviith: "Move between Headers on a page",
        UAmmbAV: "Headers",
        UAwCyWifX: "Single",
        UATIwjUIsD: "Line spacing: 1.5",
        UAMEhYzF: "Line spacing: Double",
        UAkNhbuPNz: "Line spacing: ",
        UAnysnpm: "Letter spacing: ",
        UAMQYyWwP: "Word spacing: ",
        UANbRexrt: " Turn off ",
        UAnUStik: " Finish ",
        UAYDONCOxZ: " Reset ",
        UAKTNezki: "line spacing",
        UANQBFkurJ: "Letters Spacing",
        UAhoRsVU: "Words Spacing",
        UAnomRr: "Camera navigation",
        UANZpdSY: "Click for this message to no longer appear",
        UAIbjHp: "OK",
        UAplmoJB: "right click on the mouse, a accessibility menu  will show.",
        UAKzYNDez: "open the accessibility menu  from anywhere  Click F10",
        UAIfdKEAMT: "Open Accessibility Menu",
        UAFdzfnL: "U.A - User accessibility Ltd &copy; 2018",
        UAlBSSm: "Devices Support ",
        UAYgbrE: "Voice support",
        UAIlLcZjJI: "Sign Language",
        UAukvGQU: "add\tscreen reader support",
        UAhEpGZXO: "Navigate by letters",
        UAORASv: "Highlight focus",
        UAXhBPdjlu: "VirUARlAcVM keyboard",
        UAdtClaMu: "Big white mouse",
        UAmqiBWpIt: "Big black mouse",
        UACrWJRx: "right click menu",
        UAoCvtlzM: "Adjust Navigation",
        UAKgUWfbsm: "Color Adjust",
        UARXkXIELm: "Text color",
        UApQGmaKwU: "Header color",
        UArguur: "Background color",
        UAWzOSWIB: "Dark background",
        UArwLnSeY: "Light background",
        UAqhEKU: "Gray scale",
        UAoUfxEjny: "Adjust color contrast",
        UAIadWmKn: "Content Assist",
        UApcbshkqB: "show hidden info",
        UAyOyAtL: "Highlight Links",
        UAGwfXNLtf: "Accessible printing",
        UAuqlSQI: "Acronyms",
        UAdIMSpn: "Spotted text",
        UAtshOR: "Concepts and phrases",
        UAqmXtL: "Easy reading",
        UATfxEbgm: "Target content area",
        UAZPKnHTtt: "Help with content",
        UADwBsPC: "Text Adjust",
        UABkDzVmy: "Align left",
        UAgEMnLAB: "Align right",
        UAsUwsSo: "words Spacing",
        UAhqZyIsHy: "Spacing letters",
        UAITPRDWu: "line spacing",
        UAVxbYsHNZ: "Readable font",
        UAbbhtqy: "Increase text",
        UAbQwNg: "Decrease text",
        UASvTcVza: "magnifying glass",
        UAEvcuaKY: "Adjust text",
        UAMlEqgF: "Return to the previous screen",
        UAUtlNI: "Adjust the site for you",
        UAAFpcu: "Set basic accessibility",
        UAMGPMVtwY: "Close the Accessibility menu",
        UAPyRnk: "Increase the Accessibility menu",
        UAUsWeHca: "Change the menu opening direction",
        UAJuBEtq: "Settings",
        UAbVeykQJs: "feedback",
        UAXAgNi: "Help",
        UARiTruIOv: "Profile",
        UAnynruc: "Main",
        UAhsqErBMx: "\u05d8\u05e7\u05e1\u05d8 \u05d7\u05e1\u05e8 \u05d1\u05de\u05e2\u05e8\u05db\u05ea , \u05d1\u05d1\u05e7\u05e9\u05d4 \u05e6\u05d5\u05e8 \u05e7\u05e9\u05e8 \u05e2\u05dd \u05d4\u05de\u05e0\u05d4\u05dc"

	}
}